language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --configuration=production --base-href /interfaceGenerator/
  - if [ -f src/404.html ]; then mv src/404.html dist/404.html; else cp dist/index.html dist/404.html; fi 
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/interfaceGenerator/
  on:
    branch: master
